### ISSUE TITLE
Tools for scaling up -> web links need to be checked

### ISSUE THREAD

**Issue by JacekHoleczek** [hsf-training/hsf-training-scikit-hep-webpage#56]
For example, I noticed that in the "[`Tools for scaling up`](https://hsf-training.github.io/hsf-training-scikit-hep-webpage/07-scaling-up/index.html)" chapter, the "`Uproot`" link is "`[GitHub](https://github.com/scikit-hep/uproot4)`" (note "**`uproot4`**", but it should be "`uproot5`" now).

BTW. Well, I think I am done with going through the tutorial.

**Comment by jpivarski** [comment]
For what it's worth the URL redirects. (I've left a lot of uproot4 URLs in my local bookmarks.)

Thanks for all of your feedback!
